/**
 * UI text, Russian and English.
 *
 * `Dict` is inferred from the Russian dictionary and the English one is typed
 * against it, so a key added to one and forgotten in the other is a build error
 * rather than a blank label at runtime.
 */

export const RU = {
  app: {
    name: "lil download",
    tagline: "Вставь ссылку — получи файл.",
    dropHint: "Вставь ссылку или брось её сюда",
    clipboardBtn: "Вставить из буфера",
    clipboardEmpty: "В буфере пусто",
    clipboardDenied: "Система не дала прочитать буфер",
    checking: "Смотрим, что там…",
    starting: "Запускаемся…",
    quickHint: "⌘↵ — сразу в последнюю папку с текущими настройками",
  },
  appUpdate: {
    current: "Установлена",
    check: "Проверить обновления",
    checking: "Проверяем…",
    upToDate: "Свежая версия, обновлять нечего.",
    failed: "Не вышло спросить GitHub — похоже, нет сети.",
    available: (v: string) => `Вышла ${v}`,
    notes: "Что изменилось",
    download: "Скачать",
    auto: "Проверять при запуске",
    autoNote: "Это единственное соединение, которое приложение открывает само. Выключишь — не откроет ни одного, пока не попросишь.",
  },
  lang: { label: "Язык", ru: "Русский", en: "English" },
  mode: {
    toDarkTitle: "Тёмная тема",
    toDarkAria: "Включить тёмную тему",
    light: "Светлая",
    dark: "Тёмная",
    toLightTitle: "Светлая тема",
    toLightAria: "Включить светлую тему",
  },
  skins: {
    studio: { name: "Студия" },
    brutal: { name: "Бруталь" },
    riso: { name: "Ризо" },
    te: { name: "ТЕ" },
  },
  settings: {
    appearance: "Оформление",
    title: "Настройки",
    template: "Имя файла",
    templateHint: "Перетаскивай кусочки мышью, между ними можно вписать свой текст.",
    extraArgs: "Свои флаги yt-dlp",
    extraArgsHint: "Добавляются последними, поэтому перебивают пресет. Пустое поле — ничего не добавляется.",
    back: "Назад",
    limit: "Ограничить скорость",
    limitHint: "Пусто или 0 — качаем во всю ширину канала.",
    perSecond: "с",
    units: { K: "КБ/с", M: "МБ/с", Mbit: "Мбит/с" },
    tabTools: "Программы",
    tabDownload: "Скачивание",
    tabPresets: "Пресеты",
    tabLook: "Оформление",
    tabAbout: "О программе",
    theme: "Тема",
    skin: "Стиль",
    chosen: "Выбран",
    details: "Подробности",
    channelStable: "стабильная",
    channelNightly: "ночная",
    channelHint: "Ночная выходит каждый день. Когда YouTube что-то ломает, починка приезжает туда на несколько дней раньше — но её ещё никто не проверял.",
    presets: "Свои пресеты",
    presetsHint: "Собранный пресет встанет в меню качества рядом со встроенными.",
    presetAdd: "Новый пресет",
    presetNew: "Мой пресет",
    presetName: "Название",
    presetKind: "Что скачивать",
    presetVideo: "Видео со звуком",
    presetAudio: "Только звук",
    presetHeight: "Не выше",
    presetHeightAny: "как есть",
    presetFlags: "Свои флаги",
    presetDelete: "Удалить",
    presetEmpty: "Пока ни одного. Встроенных четыре — свой нужен, когда ни один из них не подходит каждый раз.",
  },
  setup: {
    title: "Нужны две программы",
    // Being upfront about *why* nothing is bundled: people are rightly wary of
    // an app that downloads executables on first launch.
    why: "yt-dlp обновляется каждые пару недель, а ffmpeg распространяется под GPL. Поэтому обе живут рядом с приложением, а не внутри него.",
    install: "Установить",
    reinstall: "Переустановить",
    installing: "Качаем…",
    extracting: "Распаковываем…",
    // Names the program instead of saying "path". A tester read the generic
    // button as "where do I want it installed" and went looking for a folder —
    // reasonable, since "yt-dlp" means nothing until someone tells you it is a
    // program you might already own.
    choose: (tool: string) => `Указать свой ${tool}`,
    chooseHint: "Уже стоит в системе? Покажи, где лежит — своя копия качаться не будет.",
    chooseDialog: (tool: string) => `Выбери файл ${tool}`,
    found: "Нашлось",
    origin: { managed: "своя копия", custom: "указана вручную", system: "системная" },
    ytdlpWhat: "Скачивает. Без неё не работает ничего.",
    ffmpegWhat: "Склеивает видео со звуком и конвертирует. Без неё многое скачается без звука.",
    ready: "Всё на месте",
    later: "Потом",
  },
  card: {
    download: "Скачать",
    dest: "Куда",
    rememberFolder: "Запомнить эту папку",
    rememberSource: "Запомнить для этого источника",
    // PLAN §4 — the playlist is already off; this is the way back in.
    playlistFound: "В ссылке был плейлист",
    playlistCount: (n: number) => `${n} видео`,
    playlistAll: "Скачать целиком",
    timecode: "В ссылке таймкод",
    timecodeUse: "Начать с него",
    clear: "Убрать",
  },
  presets: {
    max: {
      name: "Лучшее качество",
      note: "как отдал сайт, ничего не пережимаем",
      tech: "лучшее видео + лучший звук, склейка без перекодирования",
    },
    compatible: {
      name: "Откроется везде",
      note: "mp4 — плеер, телефон, монтаж",
      tech: "H.264 до 1080p + AAC в mp4",
    },
    audio: { name: "Только звук", note: "без картинки", tech: "лучшая звуковая дорожка" },
    compact: { name: "Полегче файл", note: "720p, качается быстро", tech: "видео до 720p + звук" },
  },
  queue: {
    title: "Очередь",
    empty: "Пока пусто",
    cancel: "Остановить",
    starting: "Запускаем…",
    reveal: "Показать в папке",
    remove: "Убрать",
    removeWithFile: "Убрать из списка. С ⌘ — заодно отправить файл в корзину",
    trashed: "Файл в корзине",
    done: "Готово",
    failed: "Не вышло",
    cancelled: "Остановлено",
    again: "Изменить и скачать",
    copy: "Скопировать ссылку",
    copied: "Ссылка скопирована",
    clear: "Очистить историю",
    viewList: "Списком",
    viewBento: "Плитками",
    of: "из",
    eta: "осталось",
  },
  update: {
    stale: "yt-dlp устарел",
    // The whole point of naming the symptom: a 403 reads like a permissions
    // problem, so people go hunting for cookies instead of updating.
    why: "YouTube будет отдавать 403 на самих файлах, хотя список качеств приходит нормально.",
    have: "стоит",
    latest: "есть",
    update: "Обновить",
    updating: "Обновляем…",
    updated: "Обновили до",
    check: "Проверить версии",
    checking: "Проверяем…",
    upToDate: "Свежая",
    unknown: "неизвестно",
    lastChecked: "Проверено",
    never: "ещё не проверяли",
    noCheck: "версия не сверяется — у сборок ffmpeg нумерация своя у каждого сборщика",
    runnerPython: "лёгкий вариант, через python",
    runnerNative: "отдельный бинарь",
    startup: "запуск",
    slowHint: "Запускается очень долго. Это macOS проверяет ненотаризованный 37-мегабайтный бинарь при каждом вызове. Нажми «Переустановить» — поставим 3-мегабайтный вариант, он стартует за доли секунды.",
  },
  fmt: {
    container: "Формат файла",
    quality: "Качество",
    audio: "Звук",
    auto: "как есть",
    autoHint: "Оставим тот контейнер, в котором отдал сайт. Быстро, но с YouTube это часто .webm.",
    mp4Hint: "Откроется везде: QuickTime, телефон, телевизор, монтажки. YouTube отдаёт H.264 максимум в 1080p, так что 4K тут не будет.",
    mkvHint: "Вмещает любые кодеки без перекодирования, но открывается не всем — VLC да, QuickTime нет.",
    recode: "Перекодировать, если кодеки не подошли (долго, теряется качество)",
  },
  opts: {
    res: "Размер картинки",
    resAuto: "какой есть",
    codec: "Кодек видео",
    codecAuto: "какой есть",
    codecH264: "H.264 — открывается везде",
    codecVp9: "VP9 — меньше вес",
    codecAv01: "AV1 — ещё меньше, но новый",
    acodec: "Кодек звука",
    acodecAac: "AAC — открывается везде",
    acodecOpus: "Opus — лучше на низком битрейте",
    thumb: "Обложку внутрь файла",
    flags: "Свои флаги",
    flagsTab: "Tab — подставить первый",
    flagsDangling: "— после него нужно значение. Без него yt-dlp примет за значение то, что идёт следом, и скачивание сорвётся.",
    flagGroups: {
      net: "Сеть и скорость",
      files: "Файлы на диске",
      meta: "Метаданные внутри файла",
      pick: "Что именно брать",
      subs: "Субтитры",
      live: "Эфиры",
      audio: "Звук и перекодирование",
      access: "Доступ",
      misc: "Прочее",
    },
    trim: "Обрезать",
    trimHint: "Минуты и секунды: 2:30 или 1:02:03. Пусто — целиком.",
    subs: "Субтитры",
    subsOff: "не нужны",
    subsFile: "отдельным файлом (srt)",
    subsEmbed: "вшить в контейнер",
    sponsorblock: "Вырезать спонсорские вставки",
  },
  tpl: {
    search: "Добавить кусочек — начни печатать…",
    addText: "Добавить свой текст",
    remove: "Убрать",
    move: "Перетащи мышью или двигай стрелками",
    preview: "Получится:",
    needExt: "Без расширения система не поймёт, чем открыть файл.",
    extLast: "Расширение должно стоять последним, иначе получится что-то вроде «видео.mp4Название» — такой файл не откроется.",
    addExt: "Добавить расширение",
    groups: {
      required: "Обязательное",
      main: "Основное",
      channel: "Канал и автор",
      dates: "Даты",
      meta: "Метаданные",
      playlist: "Плейлист",
      chapter: "Главы",
      episode: "Сериалы",
      track: "Музыка",
      section: "Отрезок",
      sep: "Разделители",
    },
    manual: "Написать вручную",
    visual: "Собрать из кусочков",
    manualHint: "Поля пишутся как %(title)s. Ошибка в скобках превратит поле в обычный текст в имени файла.",
  },
  cookies: {
    title: "Куки из браузера",
    why: "yt-dlp возьмёт сессию прямо из браузера. Сами куки через приложение не проходят — мы передаём только название браузера.",
    off: "без куки",
    using: "Куки из",
    keychainNote: "Система спросит доступ к связке ключей — так устроено шифрование куки у Chrome и родственников.",
    notInstalled: "не установлен",
    needsAccess: "нужен доступ",
    grant: "Открыть настройки доступа",
    // Full Disk Access is read once at launch, so the app genuinely has to be
    // restarted — saying so up front saves a "я включил, не работает".
    grantHow: "Включи lil download в списке «Полный доступ к диску» и перезапусти приложение — macOS читает это разрешение только при старте.",
    dismiss: "Понятно, не показывать",
    checking: "проверяем…",
  },
  err: {
    notALink: "Это не похоже на ссылку",
    browserOnly: "Работает только в приложении",
  },
};

export type Dict = typeof RU;

export const EN: Dict = {
  app: {
    name: "lil download",
    tagline: "Paste a link, get the file.",
    dropHint: "Paste a link or drop one here",
    clipboardBtn: "Paste from clipboard",
    clipboardEmpty: "The clipboard is empty",
    clipboardDenied: "The system wouldn't let us read the clipboard",
    checking: "Looking it up…",
    starting: "Starting up…",
    quickHint: "⌘↵ — straight to the last folder with the current settings",
  },
  appUpdate: {
    current: "Installed",
    check: "Check for updates",
    checking: "Checking…",
    upToDate: "Up to date — nothing to install.",
    failed: "Couldn't reach GitHub — looks like there's no network.",
    available: (v: string) => `${v} is out`,
    notes: "What changed",
    download: "Download",
    auto: "Check on launch",
    autoNote: "This is the only connection the app opens on its own. Turn it off and it opens none until you ask.",
  },
  lang: { label: "Language", ru: "Русский", en: "English" },
  mode: {
    toDarkTitle: "Dark theme",
    toDarkAria: "Switch to dark theme",
    light: "Light",
    dark: "Dark",
    toLightTitle: "Light theme",
    toLightAria: "Switch to light theme",
  },
  skins: {
    studio: { name: "Studio" },
    brutal: { name: "Brutal" },
    riso: { name: "Riso" },
    te: { name: "TE" },
  },
  settings: {
    appearance: "Appearance",
    title: "Settings",
    template: "File name",
    templateHint: "Drag the pieces around; type your own text between them.",
    extraArgs: "Your own yt-dlp flags",
    extraArgsHint: "Appended last, so they beat the preset. Leave empty to add nothing.",
    back: "Back",
    limit: "Speed cap",
    limitHint: "Empty or 0 — take the whole pipe.",
    perSecond: "s",
    units: { K: "KB/s", M: "MB/s", Mbit: "Mbit/s" },
    tabTools: "Tools",
    tabDownload: "Downloading",
    tabPresets: "Presets",
    tabLook: "Appearance",
    tabAbout: "About",
    theme: "Theme",
    skin: "Style",
    chosen: "Selected",
    details: "Details",
    channelStable: "stable",
    channelNightly: "nightly",
    channelHint: "Nightly ships every day. When YouTube breaks something the fix lands there days earlier — untested by anyone yet.",
    presets: "Your own presets",
    presetsHint: "A preset you build shows up in the quality menu next to the built-in ones.",
    presetAdd: "New preset",
    presetNew: "My preset",
    presetName: "Name",
    presetKind: "What to fetch",
    presetVideo: "Video with sound",
    presetAudio: "Sound only",
    presetHeight: "No taller than",
    presetHeightAny: "as is",
    presetFlags: "Your own flags",
    presetDelete: "Delete",
    presetEmpty: "None yet. There are four built in — you want your own when none of them fits every time.",
  },
  setup: {
    title: "Two programs are needed",
    why: "yt-dlp changes every couple of weeks and ffmpeg ships under the GPL. So both live next to the app rather than inside it.",
    install: "Install",
    reinstall: "Reinstall",
    installing: "Downloading…",
    extracting: "Extracting…",
    choose: (tool: string) => `Point at your own ${tool}`,
    chooseHint: "Already installed? Show where it lives and nothing will be downloaded.",
    chooseDialog: (tool: string) => `Pick the ${tool} file`,
    found: "Found",
    origin: { managed: "our copy", custom: "set by hand", system: "system" },
    ytdlpWhat: "Does the downloading. Nothing works without it.",
    ffmpegWhat: "Joins video with audio and converts. Without it a lot arrives silent.",
    ready: "All set",
    later: "Later",
  },
  card: {
    download: "Download",
    dest: "To",
    rememberFolder: "Remember this folder",
    rememberSource: "Remember for this source",
    playlistFound: "The link carried a playlist",
    playlistCount: (n: number) => `${n} videos`,
    playlistAll: "Download all of it",
    timecode: "The link has a timecode",
    timecodeUse: "Start there",
    clear: "Clear",
  },
  presets: {
    max: {
      name: "Best quality",
      note: "as the site served it, nothing re-squeezed",
      tech: "best video + best audio, merged without re-encoding",
    },
    compatible: {
      name: "Opens anywhere",
      note: "mp4 — player, phone, editor",
      tech: "H.264 up to 1080p + AAC in mp4",
    },
    audio: { name: "Audio only", note: "no picture", tech: "best audio track" },
    compact: { name: "Lighter file", note: "720p, downloads fast", tech: "video up to 720p + audio" },
  },
  queue: {
    title: "Queue",
    empty: "Nothing yet",
    cancel: "Stop",
    starting: "Starting…",
    reveal: "Show in folder",
    remove: "Remove",
    removeWithFile: "Remove from the list. With ⌘ — put the file in the Trash too",
    trashed: "File moved to the Trash",
    done: "Done",
    failed: "Failed",
    cancelled: "Stopped",
    again: "Change and download",
    copy: "Copy the link",
    copied: "Link copied",
    clear: "Clear the history",
    viewList: "As a list",
    viewBento: "As tiles",
    of: "of",
    eta: "left",
  },
  update: {
    stale: "yt-dlp is out of date",
    why: "YouTube will answer 403 on the media itself, even though the format list comes back fine.",
    have: "installed",
    latest: "available",
    update: "Update",
    updating: "Updating…",
    updated: "Updated to",
    check: "Check versions",
    checking: "Checking…",
    upToDate: "Up to date",
    unknown: "unknown",
    lastChecked: "Checked",
    never: "not yet checked",
    noCheck: "not version-checked — ffmpeg builds are numbered differently by every builder",
    runnerPython: "light build, via python",
    runnerNative: "standalone binary",
    startup: "startup",
    slowHint: "Very slow to start. That's macOS re-checking an unnotarised 37 MB binary on every call. Hit Reinstall and we'll fetch the 3 MB build, which starts in a fraction of a second.",
  },
  fmt: {
    container: "File format",
    quality: "Quality",
    audio: "Audio",
    auto: "as-is",
    autoHint: "Keep whatever container the site served. Fast, but on YouTube that's often .webm.",
    mp4Hint: "Opens anywhere: QuickTime, phone, TV, editors. YouTube's H.264 tops out at 1080p, so no 4K here.",
    mkvHint: "Holds any codec without re-encoding, but not everything opens it — VLC yes, QuickTime no.",
    recode: "Re-encode if the codecs don't fit (slow, costs quality)",
  },
  opts: {
    res: "Picture size",
    resAuto: "whatever there is",
    codec: "Video codec",
    codecAuto: "whatever there is",
    codecH264: "H.264 — opens anywhere",
    codecVp9: "VP9 — smaller",
    codecAv01: "AV1 — smaller still, but new",
    acodec: "Audio codec",
    acodecAac: "AAC — opens anywhere",
    acodecOpus: "Opus — better at low bitrates",
    thumb: "Poster inside the file",
    flags: "Own flags",
    flagsTab: "Tab — take the first",
    flagsDangling: "— needs a value after it. Without one yt-dlp takes whatever follows as that value, and the download dies.",
    flagGroups: {
      net: "Network and speed",
      files: "Files on disk",
      meta: "Metadata inside the file",
      pick: "What to take",
      subs: "Subtitles",
      live: "Live streams",
      audio: "Audio and re-encoding",
      access: "Access",
      misc: "Other",
    },
    trim: "Trim",
    trimHint: "Minutes and seconds: 2:30 or 1:02:03. Empty means the whole thing.",
    subs: "Subtitles",
    subsOff: "not needed",
    subsFile: "separate file (srt)",
    subsEmbed: "embed in container",
    sponsorblock: "Cut out sponsor segments",
  },
  tpl: {
    search: "Add a piece — start typing…",
    addText: "Add your own text",
    remove: "Remove",
    move: "Drag it, or move it with the arrow keys",
    preview: "Result:",
    needExt: "Without an extension the system won't know what opens the file.",
    extLast: "The extension has to come last, otherwise you get something like \"video.mp4Title\" — a file nothing will open.",
    addExt: "Add the extension",
    groups: {
      required: "Required",
      main: "Basics",
      channel: "Channel and author",
      dates: "Dates",
      meta: "Metadata",
      playlist: "Playlist",
      chapter: "Chapters",
      episode: "Series",
      track: "Music",
      section: "Section",
      sep: "Separators",
    },
    manual: "Type it out",
    visual: "Build from pieces",
    manualHint: "Fields are written as %(title)s. A wrong bracket turns the field into literal text in the filename.",
  },
  cookies: {
    title: "Cookies from a browser",
    why: "yt-dlp lifts the session straight from the browser. The cookies never pass through this app — we hand over only the browser's name.",
    off: "no cookies",
    using: "Cookies from",
    keychainNote: "The system will ask for Keychain access — that's how Chrome and its relatives encrypt cookies.",
    notInstalled: "not installed",
    needsAccess: "needs access",
    grant: "Open access settings",
    grantHow: "Add lil download to Full Disk Access and restart it — macOS only reads that permission at launch.",
    dismiss: "Got it, stop showing this",
    checking: "checking…",
  },
  err: {
    notALink: "That doesn't look like a link",
    browserOnly: "Only works inside the app",
  },
};

export const DICTS = { ru: RU, en: EN } as const;
